# Generated by Django 2.0.2 on 2018-06-26 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_creator_set', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='', max_length=500)),
                ('country', models.CharField(blank=True, default='', max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, null=True)),
                ('website', models.URLField(blank=True, default='')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=user.models.user_directory_path)),
                ('background', models.ImageField(blank=True, null=True, upload_to=user.models.user_directory_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('alert_new_subscribe', models.BooleanField(default=True)),
                ('alert_new_item', models.BooleanField(default=True)),
                ('alert_suggested_boards', models.BooleanField(default=True)),
                ('social_instagram', models.CharField(blank=True, default='', max_length=500)),
                ('social_twitter', models.CharField(blank=True, default='', max_length=500)),
                ('social_youtube', models.CharField(blank=True, default='', max_length=500)),
                ('social_facebook', models.CharField(blank=True, default='', max_length=500)),
                ('social_twitch', models.CharField(blank=True, default='', max_length=500)),
                ('social_pinterest', models.CharField(blank=True, default='', max_length=500)),
                ('social_vimeo', models.CharField(blank=True, default='', max_length=500)),
                ('social_weibo', models.CharField(blank=True, default='', max_length=500)),
                ('social_vk', models.CharField(blank=True, default='', max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
