# Generated by Django 2.0.2 on 2018-03-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alert_new_item',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='alert_new_subscribe',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='alert_suggested_boards',
            field=models.BooleanField(default=True),
        ),
    ]
