# Generated by Django 2.0.2 on 2018-07-05 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_blockedusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorisedUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorised_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_user_set', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_creator_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
