# Generated by Django 2.0.2 on 2018-06-17 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180617_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='social_qzone',
        ),
    ]
