# Generated by Django 2.0.2 on 2018-07-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_authorisedusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorisedusers',
            name='authorised_user',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='blockedusers',
            name='blocked_user',
            field=models.TextField(blank=True, default=''),
        ),
    ]
