# Generated by Django 2.0.2 on 2018-07-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180705_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorisedusers',
            name='authorised_user',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='blockedusers',
            name='blocked_user',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
