# Generated by Django 2.0.2 on 2019-01-02 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20190102_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='board_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='item_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reviews_count',
        ),
    ]
