# Generated by Django 2.0.2 on 2019-03-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_profile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pro_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
