# Generated by Django 2.0.2 on 2018-06-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='board_type',
        ),
        migrations.AddField(
            model_name='itemconnection',
            name='rating',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='itemconnection',
            name='review',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
