# Generated by Django 2.0.2 on 2018-06-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='board',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
