# Generated by Django 2.0.2 on 2018-05-16 17:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='active',
        ),
        migrations.RemoveField(
            model_name='item',
            name='allow_comments',
        ),
        migrations.RemoveField(
            model_name='item',
            name='created',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_status',
        ),
        migrations.RemoveField(
            model_name='item',
            name='purchase_url',
        ),
        migrations.AddField(
            model_name='itemconnection',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='itemconnection',
            name='allow_comments',
            field=models.BooleanField(default=True, verbose_name='allow comments'),
        ),
        migrations.AddField(
            model_name='itemconnection',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemconnection',
            name='item_status',
            field=models.CharField(choices=[('WNT', 'I want this'), ('GOT', "I've got this")], default='WNT', max_length=3),
        ),
        migrations.AddField(
            model_name='itemconnection',
            name='purchase_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
