# Generated by Django 2.0.2 on 2018-05-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20180516_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_desc',
        ),
        migrations.AddField(
            model_name='itemconnection',
            name='item_desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
