# Generated by Django 2.0.2 on 2018-04-19 20:22

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20180419_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='hero',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.user_directory_path),
        ),
    ]
