# Generated by Django 2.0.2 on 2018-07-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20180630_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemconnection',
            name='review',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
