# Generated by Django 2.0.2 on 2018-07-03 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20180701_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardview',
            name='user',
        ),
    ]
