# Generated by Django 2.0.2 on 2018-05-17 19:42

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20180517_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AddField(
            model_name='itemconnection',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='defaults/no-item.png', upload_to='uploads/items/'),
        ),
    ]
