# Generated by Django 2.0.2 on 2018-07-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20180719_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemconnection',
            name='review',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
