# Generated by Django 2.0.2 on 2018-04-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20180419_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='show_video',
            field=models.BooleanField(default=False),
        ),
    ]
