# Generated by Django 2.0.2 on 2018-07-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_remove_boardview_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemconnection',
            name='original_purchase_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
