# Generated by Django 2.0.2 on 2018-07-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20180719_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemconnection',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
