# Generated by Django 2.0.2 on 2018-04-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20180423_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
