# Generated by Django 2.0.2 on 2018-08-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_itemconnection_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
