# Generated by Django 2.0.2 on 2018-04-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_remove_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='deleteable',
            field=models.BooleanField(default=True),
        ),
    ]
