# Generated by Django 2.0.2 on 2018-08-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20180801_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='recommended',
        ),
        migrations.AlterField(
            model_name='board',
            name='board_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='board',
            name='video',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='itemconnection',
            name='original_purchase_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='itemconnection',
            name='purchase_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='itemconnection',
            name='rating',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
