# Generated by Django 2.0.2 on 2018-04-28 10:15

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_board_deleteable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
