# Generated by Django 2.0.2 on 2018-08-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20180805_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemconnection',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
