# Generated by Django 2.0.2 on 2018-08-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_auto_20180805_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
