# Generated by Django 2.0.2 on 2018-05-03 19:23

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_auto_20180428_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='defaults/no-item.png', upload_to='uploads/items/'),
        ),
    ]
