# Generated by Django 2.0.2 on 2018-05-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_auto_20180503_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
