# Generated by Django 2.0.2 on 2018-08-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_board_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='board',
            name='slug',
            field=models.SlugField(default='', max_length=255),
        ),
    ]
