# Generated by Django 2.0.2 on 2018-08-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_auto_20180805_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemconnection',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
