# Generated by Django 2.0.2 on 2018-08-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0016_itemconnection_image_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemconnection',
            name='image_owner',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
