# Generated by Django 2.0.2 on 2018-08-17 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0017_auto_20180814_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemview',
            name='user',
        ),
        migrations.AlterField(
            model_name='itemview',
            name='item_conx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.ItemConnection'),
        ),
    ]
