# Generated by Django 2.0.2 on 2018-08-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0019_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='board',
        ),
        migrations.AddField(
            model_name='collection',
            name='board',
            field=models.ManyToManyField(to='board.Board'),
        ),
        migrations.RemoveField(
            model_name='collection',
            name='item_conx',
        ),
        migrations.AddField(
            model_name='collection',
            name='item_conx',
            field=models.ManyToManyField(to='board.ItemConnection'),
        ),
    ]
