# Generated by Django 2.0.2 on 2019-03-09 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0023_communities'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Communities',
            new_name='Community',
        ),
    ]
