# Generated by Django 2.0.2 on 2019-03-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0024_auto_20190309_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='products_included',
            field=models.TextField(blank=True, default=''),
        ),
    ]
