# Generated by Django 2.0.2 on 2019-03-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0025_community_products_included'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='tag',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
