# Generated by Django 2.0.2 on 2019-03-09 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0026_community_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='tag',
        ),
    ]
