# Generated by Django 2.0.2 on 2019-03-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0027_remove_community_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='tag',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
