# Generated by Django 2.0.2 on 2019-03-09 11:53

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0028_community_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='front_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='community',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.user_directory_path),
        ),
    ]
