# Generated by Django 2.0.2 on 2019-03-10 15:15

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0029_auto_20190309_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemconnection',
            name='front_page_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='community',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='defaults/no-item.png', upload_to='uploads/community/'),
        ),
    ]
